[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "Kivy_Work_Timer_package" 
version = "1.0"
authors = [
  { name="daniel908009", email="krizdaniel151@gmail.com" },
]
description = "A Kivy work timer"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "kivy",
]

[project.urls]
Homepage = "https://github.com/Daniel908009/Kivy-Work-Timer"