[tool.poetry]
name = "internal-rdbms"
version = "0.1.17"
description = ""
authors = ["Ray <ray@cruisys.com>"]
readme = "README.md"
packages = [{include = "internal", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
arrow = "^1.3.0"
pydantic-settings = "^2.2.1"
watchtower = "^3.2.0"
httpx = "^0.27.0"
dictdiffer = "^0.9.0"
sqlalchemy = "^2.0.30"
alembic = "^1.13.1"
cryptography = "^42.0.7"
aiomysql = "^0.2.0"
greenlet = "^3.0.3"
python-jose = "^3.3.0"
python-multipart = "^0.0.9"
pillow = "^10.3.0"
pillow-heif = "^0.16.0"
chardet = "^5.2.0"
apscheduler = "^3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
