[tool.poetry]
name = "mtmlib"
version = "0.4.186"
description = ""
authors = ["John Smith <john@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "mtmlib" }]


[tool.poetry-dynamic-versioning]
enable = false


style = "pep440"
vcs = "git"
bump = true
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- else -%}
        {{ serialize_pep440(base, stage, revision, dev=distance) }}
    {%- endif -%}
"""

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = ">=0.104.1"
sqlmodel = "^0.0.21"
pydantic = ">=2.5.1"
httpx = "^0.27.0"
nanoid = "^2.0.0"
python-dotenv = ">=1.0.0"
# opentelemetry-api = "^1.28.0"
# opentelemetry-sdk = "^1.28.0"
# opentelemetry-instrumentation-fastapi = "^0.47b0"
# opentelemetry-instrumentation-logging = "^0.47b0"
# opentelemetry-exporter-otlp-proto-http = "^1.28.0"

# 其他可能不需要的（下面） ====================================================================================

python-multipart = ">=0.0.6"
langchain_community = "^0.3"
langchain-core = "^0.3.6"
langgraph = ">=0.2.13"
psycopg_pool = ">=3.2.2"
# SQLAlchemy = ">=2.0.28"
# psycopg = {extras = ["binary"], version = "^3.2.1"}
psycopg = ">=3.2.1"
# numexpr = "^2.10.1"
pyjwt = "^2.9.0"
# passlib = "^1.7.4"
# psycopg-pool = "^3.2.2"
# aiosqlite = "^0.20.0"

json_repair  = ">=0.25.2"
colorama = "^0.4.6"
markdown = "^3.6"
jinja2 = "^3.1.4"
# langgraph-checkpoint-postgres = "^1.0.4"
email-validator = "^2.2.0"
emails = "^0.6"
pgvector = "^0.3.2"
wikipedia = "^1.4.0"
# 其他 ------------------------------------------------------------------
# crewai = "^0.51.1"
# unstructured = "^0.15.0"
beautifulsoup4 = ">=4.12.2"
pillow = "^10.4.0"
# langchain = "^0.2.10"




#llama-index-core = ">=0.12.0"
python-logging-loki = "^0.3.1"
pygithub = "^2.3.0"
[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.2"
types-passlib = "^1.7.7.20240106"
# python-dotenv = "1.0.0"
# inngest = "^0.4.8"
build = "^1.2.1"
twine = "^5.1.1"
debugpy = "^1.8.5"
pylint = "^3.2.6"
pytest-asyncio = "^0.23.8"
coverage = "^7.6.0"
# ipykernel = "^6.29.4"
jupyter = "^1.0.0"
nbconvert = "^7.16.3"
poethepoet = "^0.26.0"
pyright = "^1.1.371"
pytest = "^8.3.2"
pytest-timeout = "^2.3.1"
ruff = "^0.5.2"
semversioner = "^2.0.3"
update-toml = "^0.2.1"
pytest-watch = "^4.2.0"
mistune = "^3.0.2"
playwright = ">=1.39.0"
md2pdf = ">=1.0.1"
wikipedia = "^1.4.0"
jinja2 = ">=3.1.2"
newspaper3k = ">=0.2.8"


plotly = "^5.22.0"
together = "^1.2.3"
datashaper = "^0.0.49"
markdown = ">=3.5.1"
colorama = ">=0.4.6"
environs = "^11.0.0"
pyyaml = ">=6.0.1"
uvicorn = ">=0.24.0.post1"
htmldocx = "^0.0.6"
python-docx = "^1.1.0"
lxml = { version = ">=4.9.2", extras = ["html_clean"] }
tiktoken = ">=0.7.0"
json5 = "^0.9.25"
tavily-python = ">=0.2.8"
arxiv = ">=2.0.0"
PyMuPDF = ">=1.23.6"



# toml = "^0.10.2"
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"



[tool.poe.tasks]
_sort_imports = "ruff check --select I --fix . --preview"
_format_code = "ruff format  . --preview"
_ruff_check = 'ruff check . --preview'
_pyright = "pyright"
_convert_local_search_nb = 'jupyter nbconvert --output-dir=docsite/posts/query/notebooks/ --output="{notebook_name}_nb" --template=docsite/nbdocsite_template --to markdown examples_notebooks/local_search.ipynb'
_convert_global_search_nb = 'jupyter nbconvert --output-dir=docsite/posts/query/notebooks/ --output="{notebook_name}_nb" --template=docsite/nbdocsite_template --to markdown examples_notebooks/global_search.ipynb'
_semversioner_release = "semversioner release"
_semversioner_changelog = "semversioner changelog > CHANGELOG.md"
_semversioner_update_toml_version = "update-toml update --path tool.poetry.version --value \"$(semversioner current-version)\" pyproject.toml"
coverage_report = 'coverage report --omit "**/tests/**" --show-missing'
check_format = 'ruff format . --check --preview'
fix = "ruff  --preview check --fix ."
fix_unsafe = "ruff check --preview --fix --unsafe-fixes ."

_test_all = "coverage run -m pytest ./mtmai/tests"
test_unit = "pytest ./mtmai/tests/unit"
test_integration = "pytest ./mtmai/tests/integration"
test_smoke = "pytest ./mtmai/tests/smoke"
index = "python -m graphrag.index"
query = "python -m graphrag.query"
prompt_tune = "python -m graphrag.prompt_tune"
# Pass in a test pattern
test_only = "pytest -s -k"
watch_tests = "ptw --onfail 'notify-send Test Failed' --runner 'poetry run pytest'"
publish = "python -m mtmai release"
init = "python -m mtmai init"
clean = "python -m mtmai clean"





[[tool.poe.tasks.release]]
sequence = [
    '_semversioner_release',
    '_semversioner_changelog',
    '_semversioner_update_toml_version',
]
ignore_fail = 'return_non_zero'

[[tool.poe.tasks.convert_docsite_notebooks]]
sequence = ['_convert_local_search_nb', '_convert_global_search_nb']
ignore_fail = 'return_non_zero'



[[tool.poe.tasks.format]]
sequence = ['_sort_imports', '_format_code']
ignore_fail = 'return_non_zero'

[[tool.poe.tasks.check]]
sequence = ['check_format', '_ruff_check', '_pyright']
ignore_fail = 'return_non_zero'

[[tool.poe.tasks.test]]
sequence = ['_test_all', 'coverage_report']
ignore_fail = 'return_non_zero'

[tool.ruff]
target-version = "py310"
extend-include = ["*.ipynb"]
exclude = ["alembic"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.mypy]
strict = true
exclude = ["venv", ".venv", "alembic"]


[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments in functions

    "E4",
    "E7",
    "E9",
    "W291",
    "YTT",
    "T10",
    "ICN",
    "INP",
    "Q",
    "RSE",
    "SLOT",
    "INT",
    "FLY",
    "LOG",
    "C90",
    "T20",
    "D",
    "RET",
    "PD",
    "N",
    "PIE",
    "SIM",
    "S",
    "G",
    "ERA",
    "ASYNC",
    "TID",
    "UP",
    "SLF",
    "BLE",
    "C4",
    "I",
    "F",
    "A",
    "ARG",
    "PTH",
    "RUF",
    "B",
    "TCH",
    "DTZ",
    "PYI",
    "PT",
    "EM",
    "TRY",
    "PERF",
    "CPY",
    # "FBT", # use named arguments for boolean flags
    # "TD", # todos
    # "FIX", # fixme
    # "FURB" # preview rules
    # ANN # Type annotations, re-enable when we get bandwidth
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
    "B904",  # Allow raising exceptions without from e, for HTTPException
    # Deprecated Rules
    "ANN101",
    "ANN102",
    # Conflicts with interface argument checking
    "ARG002",
    "ANN204",
    # TODO: Inspect these pandas rules for validity
    "PD002", # prevents inplace=True
    # TODO RE-Enable when we get bandwidth
    "PERF203", # Needs restructuring of errors, we should bail-out on first error
    "C901",    # needs refactoring to remove cyclomatic complexity
    "D100",
    "D101",
    "D102",
    "D103",
    "D205",
    "D200",
    "T201", # 允许print 语句
    "D400",
    "D401",
    "D104",
    "ERA001",  # 允许临时注释的代码块,
    "RET504",
    "RET505",  # 允许非必要的else
    "N806", # 允许 camelCase 变量名
    "N815",
    "S101",
]


[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S", "D", "ANN", "T201", "ASYNC", "ARG", "PTH", "TRY"]
"*_test.py" = ["S", "D", "ANN", "T201", "ASYNC", "ARG", "PTH", "TRY"]
"test_*.py" = ["S", "D", "ANN", "T201", "ASYNC", "ARG", "PTH", "TRY"]
"examples/*" = ["S", "D", "ANN", "T201", "PTH", "TRY", "PERF"]
"graphrag/index/config/*" = ["TCH"]
"*.ipynb" = ["T201"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["input", "id", "bytes"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"


# https://github.com/microsoft/pyright/blob/9f81564a4685ff5c55edd3959f9b39030f590b2f/docs/configuration.md#sample-pyprojecttoml-file
[tool.pyright]
include = ["mtmai", "tests", "examples", "examples_notebooks"]
exclude = ["**/node_modules", "**/__pycache__"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
timeout = 600


[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
