[project]
name = "sqlmodelgen"
version = "0.0.1"
description = "Generate SQLModel code from SQL"
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sqloxide>=0.1.51",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
    "coverage>=7.6.9"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]