[project]
name = "aftonfalk"
version = "1.7.1"
authors = [
  { name="Erik Bremstedt", email="erik.bremstedt@gmail.com" },
]
description = "Makes it easier to interact with sql server using python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pendulum==3.0.0",
    "pyodbc==5.1.0"
]

[project.urls]
Homepage = "https://github.com/ebremstedt/aftonfalk"
Issues = "https://github.com/ebremstedt/aftonfalk/issues"
