[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "probetheus"
version = "0.1.6"
authors = [
    { name = "SemiQuant", email = "Jason.Limberis@ucsf.edu" }
]
description = "A Python package to design probes against overrepresented sequences in a fastq file."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "biopython>=1.81",
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
    "edlib>=1.3.9",
    "kneed>=0.8.1",
    "click>=8.1.0"
]

[project.scripts]
probetheus = "probetheus.cli:main"