[project]
name = "airtake"
version = "0.2.0"
description = "Airtake"
readme = "README.md"
authors = [
    { name = "Bae Junehyeon", email = "devunt@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "nanoid>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
