[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "aldepyde"
version = "0.0.0a1"
authors = [
  { name="Nate McMurray", email="nate.mcmurray13@gmail.com" },
]
description = "A package of chemistry and biochemical tools"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["chemistry", "biochemistry", "protein", "dna", "rna", "pdb", "mmcif"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/cathepsin/aldepyde"
Issues = "https://github.com/cathepsin/aldepyde/issues"
Changelog = "https://github.com/cathepsin/aldepyde/blob/main/Changelog.md"