[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentCores"
version = "0.2.4"
dependencies = ["pymongo", "duckduckgo_search"]
description = "A flexible framework for creating and managing AI agent configurations"
readme = "README.md"
authors = [{name = "Leo Borcherding"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["ai", "agents", "llm", "framework"]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/Leoleojames1/agentCores"
Issues = "https://github.com/Leoleojames1/agentCores/issues"