[tool.poetry]
name = "nonebot-plugin-addons-manager"
version = "0.1.1"
description = "nonebot plugin that can help manage addons folder in valve's game"
authors = ["ScorMax <1335900872@qq.com>"]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
nonebot2 = "^2.4.0"
aiohttp = "^3.11.10"
nonebot-adapter-onebot = "^2.4.6"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
