[project]
name = "naneos-devices"
version = "1.0.48"
description = "Naneos gmbh python backend"
readme = "README.md"
readme-content-type = "text/markdown"
authors = [
    { name = "Mario Huegi", email = "mario.huegi@naneos.com" }
]
repository = "https://github.com/naneos-org/python-naneos-devices"
documentation = "https://naneos-org.github.io/python-naneos-devices/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.12"
dependencies = [
    "bleak>=0.22.3",
    "influxdb-client[ciso]>=1.48.0",
    "pandas>=2.2.3",    
    "protobuf>=5.29.2",
    "pyserial>=3.5",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "simplepyble>=0.8.1",
    "typer>=0.15.1",
]

[tool.uv]
environments = [
    "sys_platform == 'darwin'",
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/naneos"]

[[tool.uv.index]]
explicit = true
name = "testpypi"
publish-url = "https://test.pypi.org/legacy"
url = "https://test.pypi.org/simple"