[tool.poetry]
name = "pynbntnmodem"
version = "0.2.11"
description = "Library for interfacing to Narrowband Non-Terrestrial Network modems using AT commands."
authors = ["geoffbrucepayne <geoff.bruce-payne@inmarsat.com>"]
license = "Apache2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyatcommand = "^0.3.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pylint = "^3.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
