[project]
name = "tts-evaluate-yue"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sagewe", email = "sagewe@fastmail.com" }
]
dependencies = [
    "evaluate",
    "jiwer",
    "faster_whisper",
    "yue_normalizer",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
