[project]
name = "video-editor-mcp"
version = "0.1.13"
description = "Video Jungle MCP Server for Adding, Analysing, Searching, and Editing Videos"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "mcp>=1.0.0",
 "videojungle>=0.1.25",
]
homepage = "https://github.com/burningion/video-editing-mcp"

[[project.authors]]
name = "Kirk Kaiser"
email = "kirk@zothcorp.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = ["tools"]

[project.scripts]
video-editor-mcp = "video_editor_mcp:main"

[project.urls]
Homepage = "https://github.com/burningion/video-editing-mcp"
Issues = "https://github.com/burningion/video-editing-mcp/issues"
