[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "axinite"
version = "1.4.1"
dependencies = ["astropy", "numpy"]
authors = [{ name = "Jewels", email = "jewels286@proton.me" }]
maintainers = [{ name = "Jewels", email = "jewels286@proton.me" }]
description = "A powerful open-source engine for advanced celestial mechanics."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["celestial-mechanics", "orbital-dynamics", "engine"]
classifiers = [
	"Development Status :: 4 - Beta"
]

[project.urls]
Homepage = "https://jewels86.me/axinite"
Documentation = "https://jewels86.gitbook.io/axinite"
Repository = "https://github.com/jewels86/axinite"

[project.optional-dependencies]
tools-no-frontends = ["json", "itertools"]
tools = ["vpython", "plotly", "vtk", "mayavi", "pyqt5", "json", "itertools"]
tools-vpython = ["json", "itertools"]
tools-plotly = ["json", "itertools", "plotly"]
tools-mayavi = ["json", "itertools", "vtk", "pyqt5", "mayavi"]

[tool.setuptools.packages.find]
where = ["axinite"]
exclude = ["test.py"]