



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "prosthetic"
version = "2.1.0"
description = "How to organize"
authors = []
readme = "parties/prosthetic/readme.md"
keywords = [
	"leads",
	"organization"
]
license = "AGPL-3.0-only"


packages = [
    { include = "prosthetic", from = "parties" }
]
exclude = [
	"parties/prosthetic/_status/constellations"
]
include = [ 
	"parties/prosthetic/sveltnetics_packets/**/*",
	"*.HTML",
	"*.html", 
	"*.JSON", 
	"*.json" 
]



[tool.poetry.dependencies]
python = "^3.10"
biotech = "^1.1.10"
click = "^8.1.7"
deepmerge = "^1.1.1"
Emergency = "^2.0.0"
Flask = "^3.1.0" 
ships = "^1.8.0"
somatic = "^3.0.1"
law_dictionary = "^1.0.12"
pika = "^1.3.2"
pydash = "^8.0.1"
pymongo = "^4.7.2"
rich = "^13.7.1"
tinydb = "^4.8.0"
setuptools = "^69.5.1"
sanic = "^23.12.1"
sanic-ext = "^23.12.0"
sanic_limiter = "0.1.3"
ventures = "^1.6.0"


[tool.poetry.scripts]
prosthetic = 'prosthetic:clique'

[tool.poetry.urls]
GitLab = "https://gitlab.com/status600/treasures/prosthetic.1"



