[tool.poetry]
name = "browselite"
version = "0.0.1"
description = "automated browsing"
authors = ["Kammari Santhosh"]
readme = "README.md"
license = "MIT License"
repository = "https://github.com/santhosh/"
keywords = [""]
packages = [
    {include = "browselite"}
]
include = [
#    "vision_gui.py",
#    "vision_run.py"
]

[tool.poetry.dependencies]
python = "^3.10"
pyperclip="^1.9.0"
pyautogui = "^0.9.52"

[tool.poetry.dev-dependencies]


#[tool.poetry.scripts]
#vision-gui = "vision_gui:run_app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"