[project]
name = "taolib"
version = "0.0.1"
description = "道可道，非恒道"
authors = [
    { name = "xinetzone", email = "735613050@qq.com" },
]
requires-python = ">=3.10"
readme = "README.md"
maintainers = [
    { name = "xinetzone", email = "735613050@qq.com" },
]
dependencies = [
    "xyzstyle",
    "sphinx",
]

[project.license]
file = "LICENSE"

[project.urls]
Repository = "https://github.com/xinetzone/tao"
Documentation = "https://taolib.readthedocs.io/"

[project.optional-dependencies]
doc = [
    "ablog",
    "ipywidgets",
    "folium",
    "numpy",
    "matplotlib",
    "numpydoc",
    "myst-nb",
    "nbclient",
    "pandas",
    "plotly",
    "sphinx-design",
    "sphinx-examples",
    "sphinx-copybutton",
    "sphinx-tabs",
    "sphinx-togglebutton",
    "sphinx-thebe",
    "sphinxcontrib-bibtex",
    "sphinxcontrib-youtube",
    "sphinxext-opengraph",
    "sphinx-sitemap",
    "sphinx-autoapi",
    "graphviz",
]
flows = [
    "invoke",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
