[project]
name = "mcp-sse-shim"
version = "0.1.22"
description = "shim for mcp sse over stdio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.10",
]

[project.scripts]
mcp-sse-shim = "shim.shim:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["shim"]

