[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "asteroid_sdk",
    "asteroid_sdk.supervision",
    "asteroid_sdk.registration",
    "asteroid_sdk.utils",
    "asteroid_sdk.wrappers"
]

[tool.setuptools.package-data]
asteroid_sdk = ["py.typed"]  # If you want to support type hints

[project]
name = "asteroid_sdk"
version = "0.1.6"
description = "A Python SDK for Asteroid"
authors = [
    { name = "Asteroid", email = "founders@asteroid.ai" }
]
license = { file = "LICENSE" }
readme = "README.md"
dependencies = [
    "requests>=2.28.0",
    "openai>=1.0.0",
    "anthropic>=0.3.0",
    "litellm>=0.1.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "inspect-ai>=0.3.49",
    "jinja2>=3.1.4"
]

[project.entry-points.inspect_ai]
asteroid_sdk = "asteroid_sdk.supervision.inspect_ai._registry"
