[tool.poetry]
name = "auto-prep"
version = "0.1.0"
description = "Automated preprocessing pipeline with LaTeX report generation and visualization"
authors = ["Pawe≈Ç Pozorski <pozorski.paul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.0"
numpy = "^1.23.0"
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
matplotlib = "^3.5.1"
pylatex = "^1.4.1"
feature-engine = "^1.4.1"
optuna = "^2.10.0"
pandas-profiling = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^5.0.0"
autoflake = "^1.4.0"
pre-commit = "^3.5.0"

[tool.poetry.scripts]
format = "scripts.format:main"
lint = "scripts.lint:main"
check = "scripts.check:main"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/docs
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.autoflake]
check = true
recursive = true
remove-all-unused-imports = true
remove-unused-variables = true
exclude = ["__init__.py"]
expand-star-imports = true
ignore-init-module-imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
