[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "replbase"
version = "0.0.2"
description = "\"Combination of other REPL tools into a reusable class that generates a REPL\""
authors = [ "Joseph Bochinski <stirgejr@gmail.com>",]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ptpython = "^3.0.29"
rich = "^13.9.4"
prompt-toolkit = "^3.0.48"
pyyaml = "^6.0.2"
argcomplete = "^3.5.2"
